from typing import Literal

from pydantic import Field

from inspect_ai.event._base import BaseEvent
from inspect_ai.tool._tool_call import ToolCall


class ReviewEvent(BaseEvent):
    """Tool result review."""

    event: Literal["review"] = Field(default="review")
    """Event type"""

    message: str
    """Message generated by model along with tool call."""

    call: ToolCall
    """Tool call whose result was reviewed."""

    reviewer: str
    """Reviewer name."""

    decision: Literal["continue", "terminate", "escalate"]
    """Decision of reviewer."""

    explanation: str | None = Field(default=None)
    """Explanation for decision."""
