"""Check inspect-openapi.json for structural drift, tolerating doc-only changes.

Compares the committed schema (git HEAD) against the working-tree schema
(freshly regenerated by schema.py). Documentation text — string-valued
"description" keys, which come from Python docstrings — is ignored so that
docstring-only changes don't require regenerating the schema. Any other
difference fails.

A schema *field* literally named "description" (e.g. ToolInfo.description)
is unaffected: its value is a schema object, not a string.

Usage:
    python .github/scripts/check_openapi_drift.py
"""

import difflib
import json
import subprocess
import sys

SCHEMA_PATH = "src/inspect_ai/_view/inspect-openapi.json"

# Keys whose values are data payloads, not schema. A "description" key nested
# inside these is data and must compare exactly.
DATA_KEYS = {"default", "examples", "const", "enum"}


def strip_docs(node: object) -> object:
    if isinstance(node, dict):
        return {
            k: (v if k in DATA_KEYS else strip_docs(v))
            for k, v in node.items()
            if not (k == "description" and isinstance(v, str))
        }
    if isinstance(node, list):
        return [strip_docs(item) for item in node]
    return node


def main() -> int:
    committed = json.loads(
        subprocess.run(
            ["git", "show", f"HEAD:{SCHEMA_PATH}"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    )
    with open(SCHEMA_PATH) as f:
        regenerated = json.load(f)

    old, new = strip_docs(committed), strip_docs(regenerated)
    if old == new:
        return 0

    old_lines = json.dumps(old, indent=2, sort_keys=True).splitlines(keepends=True)
    new_lines = json.dumps(new, indent=2, sort_keys=True).splitlines(keepends=True)
    sys.stdout.writelines(
        difflib.unified_diff(old_lines, new_lines, "committed", "regenerated")
    )
    print(f"\n{SCHEMA_PATH} has structural (non-docstring) changes. Please run:")
    print("  python src/inspect_ai/_view/schema.py")
    return 1


if __name__ == "__main__":
    sys.exit(main())
