from typing import Protocol

from inspect_ai.model._chat_message import ChatMessage, ChatMessageTool
from inspect_ai.tool._tool import ToolResult
from inspect_ai.tool._tool_call import ToolCall, ToolCallView

from ._review import Review


class Reviewer(Protocol):
    """Protocol for reviewers."""

    async def __call__(
        self,
        message: str,
        call: ToolCall,
        result: ChatMessageTool,
        output: ToolResult,
        view: ToolCallView,
        history: list[ChatMessage],
    ) -> Review:
        """
        Review the result of a tool call that has executed.

        Args:
            message: Message generated by the model along with the tool call.
            call: The tool call that executed (as executed, after any
                call-stage modification by an approver).
            result: The tool result as the model will see it (after output
                truncation), including any tool error.
            output: The tool's untruncated return value.
            view: Custom rendering of tool context and call.
            history: The current conversation history (ending with the
                assistant turn that made the call).

        Returns:
            Review: A Review object containing the decision and explanation.
        """
        ...
