from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import datetime
from logging import getLogger
from typing import (
    Any,
    Callable,
    Literal,
    ParamSpec,
    Protocol,
    Type,
    Union,
    overload,
    runtime_checkable,
)

from pydantic import BaseModel, ConfigDict, Field, model_serializer

from inspect_ai._util.error import PrerequisiteError
from inspect_ai._util.metadata import MT, metadata_as
from inspect_ai._util.registry import (
    RegistryInfo,
    is_registry_object,
    registry_add,
    registry_create,
    registry_info,
    registry_name,
    registry_params,
    registry_tag,
)

logger = getLogger(__name__)

CORRECT = "C"
"""Value to assign for correct answers."""

INCORRECT = "I"
"""Value to assign for incorrect answers."""

PARTIAL = "P"
"""Value to assign for partial credit."""

NOANSWER = "N"
"""Value to assign for no answer or refusal to answer."""


Value = Union[
    str | int | float | bool,
    Sequence[str | int | float | bool],
    Mapping[str, str | int | float | bool | None],
]
"""Value provided by a score.

Use the methods of `Score` to easily treat
the `Value` as a simple scalar of various types.
"""

UNCHANGED: Literal["UNCHANGED"] = "UNCHANGED"
"""Sentinel value to indicate an unchanged field in score edits."""


class ProvenanceData(BaseModel):
    """Metadata about who made an edit and why."""

    timestamp: datetime = Field(default_factory=datetime.now)
    """Timestamp when the edit was made."""

    author: str
    """Author who made the edit."""

    reason: str | None = Field(default=None)
    """Reason for the edit."""

    metadata: dict[str, Any] = Field(default_factory=dict)
    """Additional metadata about the edit."""


class ScoreEdit(BaseModel):
    """A single edit to a score."""

    model_config = ConfigDict(validate_assignment=True)

    value: Value | Literal["UNCHANGED"] = "UNCHANGED"
    """New value for the score, or UNCHANGED to keep current value."""

    answer: str | None | Literal["UNCHANGED"] = "UNCHANGED"
    """New answer for the score, or UNCHANGED to keep current answer."""

    explanation: str | None | Literal["UNCHANGED"] = "UNCHANGED"
    """New explanation for the score, or UNCHANGED to keep current explanation."""

    metadata: dict[str, Any] | Literal["UNCHANGED"] = "UNCHANGED"
    """New metadata for the score, or UNCHANGED to keep current metadata."""

    provenance: ProvenanceData | None = None
    """Provenance data for this edit. None indicates this is the original score."""

    @classmethod
    def model_validate(cls, obj: Any, **kwargs: Any) -> "ScoreEdit":
        """Override validation to handle explicit None values in JSON."""
        if isinstance(obj, dict):
            # If JSON explicitly contains null values, preserve them as None
            # instead of letting Pydantic default them to "UNCHANGED"
            obj_copy = obj.copy()
            for field in ["answer", "explanation"]:
                if field in obj and obj[field] is None:
                    # Explicitly preserve None values
                    obj_copy[field] = None
            obj = obj_copy

        return super().model_validate(obj, **kwargs)

    def model_dump(self, **kwargs: Any) -> dict[str, Any]:
        """Override model_dump to preserve None values for round-trip compatibility."""
        # Always include None values for fields that can be None
        kwargs.setdefault("exclude_none", False)
        return super().model_dump(**kwargs)

    def __init__(self, **kwargs: Any) -> None:
        """Override init to handle None values properly."""
        # Key insight: if provenance is explicitly set to None, this is an original score
        # If provenance is not provided at all, this is an edit with default provenance (None)
        # If provenance is provided with a ProvenanceData object, this is an edit with metadata

        # Check if this is an original score (provenance explicitly set to None in kwargs)
        is_original_score = "provenance" in kwargs and kwargs["provenance"] is None

        if is_original_score:
            # This is an original score - preserve None values explicitly
            # Don't let Pydantic default None to "UNCHANGED"

            # Handle each field that can be None
            for field in ["answer", "explanation"]:
                if field not in kwargs:
                    # Field completely missing - set to None for original scores
                    kwargs[field] = None
                # If field is in kwargs, keep its value (including None)

            # Metadata should default to empty dict if not provided
            if "metadata" not in kwargs:
                kwargs["metadata"] = {}
        # For edit scores (including when provenance is not specified), use Pydantic defaults

        super().__init__(**kwargs)


class Score(BaseModel):
    """Score generated by a scorer with edit history support."""

    history: list[ScoreEdit] = Field(default_factory=list)
    """Edit history - users can access intermediate states."""

    def __init__(
        self,
        value: Value | None = None,
        answer: str | None = None,
        explanation: str | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ):
        """Initialize a Score with backward compatibility."""
        # Check if this is new-style initialization (with history already provided)
        if "history" in kwargs:
            # New-style initialization - history is provided directly
            super().__init__(**kwargs)
        else:
            # Legacy-style initialization - create history from provided values
            if value is None:
                raise ValueError("Score value cannot be None")

            # First entry is the original with no provenance
            original: ScoreEdit = ScoreEdit(
                value=value,
                answer=answer,
                explanation=explanation,  # This will be None if not provided
                metadata=metadata or {},
                provenance=None,  # Indicates this is the original
            )
            super().__init__(history=[original], **kwargs)

    @classmethod
    def model_validate(cls, obj: Any, **kwargs: Any) -> "Score":
        """Override deserialization to handle both old and new formats."""
        if isinstance(obj, dict):
            # Check if this is old format (has 'value' but no 'history')
            if "value" in obj and "history" not in obj:
                # Convert old format to new format
                # For old format, missing fields should be None, not "UNCHANGED"
                explanation = obj.get("explanation")
                answer = obj.get("answer")

                # Create the score with explicit parameters to avoid defaults
                # Use **kwargs approach to trigger original score handling in ScoreEdit.__init__
                edit_kwargs = {
                    "value": obj["value"],
                    "answer": answer,
                    "explanation": explanation,
                    "metadata": obj.get("metadata", {}),
                    "provenance": None,  # Explicitly pass provenance=None to trigger original score logic
                }
                original: ScoreEdit = ScoreEdit(**edit_kwargs)
                return cls(history=[original])
            # Otherwise, use standard validation for new format
        return super().model_validate(obj, **kwargs)

    @model_serializer
    def _serialize_score(self) -> dict[str, Any]:
        """Custom serializer that works with nested Pydantic serialization."""
        return self._model_dump_impl()

    def model_dump(self, **kwargs: Any) -> dict[str, Any]:
        """Override serialization to maintain backward compatibility."""
        return self._model_dump_impl()

    def _model_dump_impl(self) -> dict[str, Any]:
        """Implementation of custom serialization logic."""
        # For new-style scores (created with history), preserve the format
        # For old-style scores (single edit with no provenance), use legacy format
        if len(self.history) == 1 and self.history[0].provenance is None:
            # This is a legacy-style score, serialize in the old format
            edit = self.history[0]
            legacy_result = {"value": edit.value}

            # Only include fields that are not None or "UNCHANGED"
            # This maintains clean legacy format for newly created scores
            # while preserving round-trip compatibility for loaded scores
            if edit.answer is not None and edit.answer != "UNCHANGED":
                legacy_result["answer"] = edit.answer
            if edit.explanation is not None and edit.explanation != "UNCHANGED":
                legacy_result["explanation"] = edit.explanation
            if edit.metadata:  # Only include if not empty
                legacy_result["metadata"] = edit.metadata

            return legacy_result
        else:
            # This is a new-style score with edits, include computed fields for compatibility
            # Get the default serialization but add computed fields
            result = {"history": [edit.model_dump() for edit in self.history]}
            result["value"] = self.value
            result["answer"] = self.answer
            result["explanation"] = self.explanation
            result["metadata"] = self.metadata
            return result

    @property
    def value(self) -> Value:
        """Returns the most recent value."""
        for edit in reversed(self.history):
            if edit.value != "UNCHANGED":
                return edit.value
        raise ValueError("No value found")  # Should never happen

    @value.setter
    def value(self, new_value: Value) -> None:
        """Set the value by adding a new edit to the history."""
        edit: ScoreEdit = ScoreEdit(value=new_value)
        self.history.append(edit)

    @property
    def answer(self) -> str | None:
        """Returns the most recent answer."""
        for edit in reversed(self.history):
            if edit.answer != "UNCHANGED":
                return edit.answer
        return None

    @property
    def explanation(self) -> str | None:
        """Returns the most recent explanation."""
        for edit in reversed(self.history):
            if edit.explanation != "UNCHANGED":
                return edit.explanation
        return None

    @property
    def metadata(self) -> dict[str, Any]:
        """Returns the most recent metadata."""
        for edit in reversed(self.history):
            if edit.metadata != "UNCHANGED":
                return edit.metadata
        return {}  # Fallback to empty dict

    @property
    def original_value(self) -> Value:
        """Returns the original value."""
        if self.history:
            return self.history[0].value
        raise ValueError("Score has no history")

    @property
    def was_edited(self) -> bool:
        """Whether this score has been edited."""
        return len(self.history) > 1

    @property
    def text(self) -> str:
        """Read the score as text."""
        return self.as_str()

    def as_str(self) -> str:
        """Read the score as a string."""
        return str(self._as_scalar())

    def as_int(self) -> int:
        """Read the score as an integer."""
        return int(self._as_scalar())

    def as_float(self) -> float:
        """Read the score as a float."""
        return float(self._as_scalar())

    def as_bool(self) -> bool:
        """Read the score as a boolean."""
        return bool(self._as_scalar())

    def as_list(self) -> list[str | int | float | bool]:
        """Read the score as a list."""
        if isinstance(self.value, list):
            return self.value
        else:
            raise ValueError("This score is not a list")

    def as_dict(self) -> dict[str, str | int | float | bool | None]:
        """Read the score as a dictionary."""
        if isinstance(self.value, dict):
            return self.value
        else:
            raise ValueError("This score is not a dictionary")

    def _as_scalar(self) -> str | int | float | bool:
        if isinstance(self.value, str | int | float | bool):
            return self.value
        else:
            raise ValueError("This score is not a scalar")


class SampleScore(BaseModel):
    """Score for a Sample."""

    score: Score
    """A score"""

    sample_id: str | int | None = Field(default=None)
    """A sample id"""

    sample_metadata: dict[str, Any] | None = Field(default=None)
    """Metadata from the sample"""

    def sample_metadata_as(self, metadata_cls: Type[MT]) -> MT | None:
        """Pydantic model interface to sample metadata.

        Args:
          metadata_cls: Pydantic model type

        Returns:
          BaseModel: Instance of metadata_cls bound to sample metadata.
        """
        if self.sample_metadata is not None:
            return metadata_as(self.sample_metadata, metadata_cls)
        else:
            return None

    scorer: str | None = Field(default=None)
    """Registry name of scorer that created this score."""


ValueToFloat = Callable[[Value], float]
"""Function used by metrics to translate from a Score value to a float value."""


def value_to_float(
    correct: Value = CORRECT,
    incorrect: Value = INCORRECT,
    partial: Value = PARTIAL,
    noanswer: Value = NOANSWER,
) -> ValueToFloat:
    """Create a ValueToFloat function.

    Create a ValueToFloat function that maps scalar values of
    different types into floats. For strings, common boolean
    representations (e.g. 'yes', 'no', 'true', 'false') are
    mapped to 1 and 0. In addition, the specified correct,
    incorrect, partial, and noanswer values (by default "C"
    "I", "P", and "N") are mapped to 1, 0, 0.5, and 0. Note that
    those are the default literal values, but they can be
    customized. Strings with only numbers are converted, and
    numeric values are cast to float. Arrays and dictionaries
    give a warning and return 0.

    Args:
       correct (Value): Value that represents a correct answer (1)
       incorrect (Value): Value that represents an incorrect answer (0)
       partial (Value): Value to assign partial credit for (0.5)
       noanswer (Value): Value for refusals to answer (0)

    Returns:
        ValueToFloat function.
    """

    def to_float(value: Value) -> float:
        if isinstance(value, int | float | bool):
            return float(value)
        elif value == correct:
            return 1.0
        elif value == partial:
            return 0.5
        elif value == incorrect or value == noanswer:
            return 0
        elif isinstance(value, str):
            value = value.lower()
            if value in ["yes", "true"]:
                return 1.0
            elif value in ["no", "false"]:
                return 0.0
            elif value.replace(".", "").isnumeric():
                return float(value)

        # couldn't extract a value
        logger.warning(f"Unable to convert value to float: {value}")
        return 0.0

    return to_float


@runtime_checkable
class MetricDeprecated(Protocol):
    def __call__(self, scores: list[Score]) -> Value: ...


@runtime_checkable
class MetricProtocol(Protocol):
    def __call__(self, scores: list[SampleScore]) -> Value:
        r"""Compute a metric on a list of scores.

        Args:
          scores: List of scores.

        Returns:
          Metric value

        Examples:
          ```python
          @metric
          def mean() -> Metric:
              def metric(scores: list[SampleScore]) -> Value:
                  return np.mean([score.score.as_float() for score in scores]).item()
              return metric
          ```
        """
        ...


Metric = MetricProtocol | MetricDeprecated
"""Metric protocol.

The Metric signature changed in release v0.3.64. Both
the previous and new signatures are supported -- you
should use `MetricProtocol` for new code as the
depreacated signature will eventually be removed.
"""


P = ParamSpec("P")


@dataclass(frozen=True)
class MetricSpec:
    """Scorer specification used to (re-)create scorers."""

    metric: str
    """Metric name"""

    args: dict[str, Any] = field(default_factory=dict)
    """Metric arguments."""


def metric_register(metric: Callable[P, Metric], name: str = "") -> Callable[P, Metric]:
    r"""Register a function or class as a metric.

    Args:
        metric (MetricType):
            Function that returns a Metric or class
            deriving fromMetric
        name (str): Name of metric (Optional, defaults to object name)

    Returns:
        Metric type with registry attributes.
    """
    metric_name = name if name else getattr(metric, "__name__")
    registry_add(metric, RegistryInfo(type="metric", name=metric_name))
    return metric


def metric_create(name: str, **kwargs: Any) -> Metric:
    r"""Create a Metric based on its registered name.

    Metrics can be functions that return a Metric or classes
    deriving from Metric

    Args:
        name (str): Name of metric (Optional, defaults to object name)
        **kwargs (dict): Optional creation arguments for the metric

    Returns:
        Metric with registry info attribute
    """
    return registry_create("metric", name, **kwargs)


def to_metric_specs(
    metrics: list[Metric] | dict[str, list[Metric]],
) -> list[MetricSpec] | dict[str, list[MetricSpec]]:
    if isinstance(metrics, list):
        return [as_metric_spec(m) for m in metrics]
    else:
        return {
            k: [as_metric_spec(v) for v in metric_list]
            for k, metric_list in metrics.items()
        }


def as_metric_spec(metric: Metric) -> MetricSpec:
    if not is_registry_object(metric):
        raise PrerequisiteError(
            f"The metric {getattr(metric, '__name__', '<unknown>')} was not created by a function decorated with @metric so cannot be recorded."
        )
    return MetricSpec(metric=registry_info(metric).name, args=registry_params(metric))


@overload
def metric(name: str) -> Callable[[Callable[P, Metric]], Callable[P, Metric]]: ...


@overload
# type: ignore
def metric(name: Callable[P, Metric]) -> Callable[P, Metric]: ...


def metric(
    name: str | Callable[P, Metric],
) -> Callable[[Callable[P, Metric]], Callable[P, Metric]] | Callable[P, Metric]:
    r"""Decorator for registering metrics.

    Args:
      name: Optional name for metric. If the decorator has no name
        argument then the name of the underlying MetricType
        will be used to automatically assign a name.

    Examples:
      ```python
      @metric
      def mean() -> Metric:
          def metric(scores: list[SampleScore]) -> Value:
              return np.mean([score.score.as_float() for score in scores]).item()
          return metric
    ```
    """

    # create_metric_wrapper:
    #  (a) Add the MetricType to the registry using the appropriately
    #      package-namespaced name
    #  (b) Ensure that instances of Metric created by MetricType also
    #      carry registry info.
    def create_metric_wrapper(
        metric_type: Callable[P, Metric], name: str | None = None
    ) -> Callable[P, Metric]:
        metric_name = registry_name(
            metric_type, name if name else getattr(metric_type, "__name__")
        )

        def metric_wrapper(*args: P.args, **kwargs: P.kwargs) -> Metric:
            metric = metric_type(*args, **kwargs)
            registry_tag(
                metric_type,
                metric,
                RegistryInfo(type="metric", name=metric_name),
                *args,
                **kwargs,
            )
            return metric

        return metric_register(metric_wrapper, metric_name)

    # for decorators with an explicit name, one more wrapper for the name
    if isinstance(name, str):

        def wrapper(metric_type: Callable[P, Metric]) -> Callable[P, Metric]:
            return create_metric_wrapper(metric_type, name)

        return wrapper

    # create a metric wrapper for the passed metric_type
    else:
        metric_type = name
        return create_metric_wrapper(metric_type)
