services:
  grafana:
    image: marshw/grafana
    init: true
    networks:
      - grafana_network
    expose:
      - 3000
    healthcheck:
      # curl is not installed in the grafana image, so use wget
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  attacker:
    image: marshw/attacker
    init: true
    command: tail -f /dev/null
    working_dir: /root
    networks:
      - grafana_network
    platform: linux/amd64
    x-default: true
    depends_on:
      - grafana

networks:
  grafana_network:
    driver: bridge
    internal: true
