services:
  spray:
    image: marshw/spray
    init: true
    networks:
      - spray_network
    expose:
      - 8082
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://0.0.0.0:8082/ || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  attacker:
    image: marshw/attacker
    init: true
    command: tail -f /dev/null
    working_dir: /root
    networks:
      - spray_network
    platform: linux/amd64
    x-default: true
    depends_on:
      - spray

networks:
  spray_network:
    driver: bridge
    internal: true
