services:
  default:
    image: aisiuk/inspect-computer-tool
    init: true

    # You can VNC into each container by using the following port mapping, which
    # dynamically binds to loopback host ports. Find the specific bindings with
    # `docker inspect <container_id_or_name>`. This info is also included in the
    # Running Samples tab. The output will look something like:
    #
    #  service   container   host     url
    #  VNC       5900        61029    vnc://localhost:61029
    #  noVNC     6080        61030    http://localhost:61030?view_only=true&autoconnect=true

    ports:
      - "127.0.0.1::5900"
      - "127.0.0.1::6080"
