FROM ubuntu:noble

RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip install --break-system-packages inspect-tool-support
RUN inspect-tool-support post-install

CMD ["tail", "-f", "/dev/null"]