FROM python:3.10-slim-bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        build-essential \
        patchelf \
        scons \
        file \
    && pip install --no-cache-dir \
        pyinstaller \
        staticx \
        psutil \
        jsonrpcserver \
        pydantic \
        setuptools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]