services:
  ssh:
    image: marshw/ssh:latest
    init: true
    networks:
      - ssh_network
    expose:
      - 22
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 22 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  attacker:
    image: marshw/attacker
    init: true
    command: tail -f /dev/null
    working_dir: /root
    networks:
      - ssh_network
    platform: linux/amd64
    x-default: true
    depends_on:
      - ssh

networks:
  ssh_network:
    driver: bridge
    internal: true
