#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Releases the inspect-sandbox-tools injectables: builds the four artifacts
# (amd64/arm64 × glibc/musl) from the PR's head branch, validates them across
# Linux distros, uploads them to S3, and commits the pinned digests back to
# the PR branch. Follows .claude/skills/release-sandbox-tools/SKILL.md and
# src/inspect_sandbox_tools/design/RELEASING.md.
#
# Run it from a checkout of the PR's head branch:
#   scripts/release-sandbox-tools.sh [--dry-run]
#
# --dry-run: build, validate, and rewrite SHA256SUMS locally (uncommitted,
# for inspection; includes the credential-free immutability check) — skips
# the S3 upload and everything downstream of it (digest commit/push,
# published-artifact verify, CI watch).
#
# --auto: unattended mode, for agents. Pauses vanish and every confirmation
# resolves to the safe answer printed at its call site; anything genuinely
# needing a human mid-run (starting Docker, aws sso login) aborts with
# instructions instead of assuming. The checks guarding the irreversible step
# (PR approval, version-vs-main, fingerprints, the upload immutability guard)
# are mechanical and run in both modes.

TOTAL_STAGES=7

DRY_RUN=0
AUTO=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --auto) AUTO=1 ;;
    *) printf 'unknown option: %s (usage: %s [--dry-run] [--auto])\n' "$arg" "$0" >&2; exit 2 ;;
  esac
done
if [[ "$AUTO" == 0 && ! -t 0 ]]; then
  printf 'stdin is not a terminal — prompts cannot be answered. Re-run with --auto.\n' >&2
  exit 2
fi

if [[ "$AUTO" == 1 ]]; then
  pause() { :; }
fi

# confirm_or y|n "question" — confirm, resolving to the given answer on
# --auto runs.
confirm_or() {
  if [[ "$AUTO" == 0 ]]; then
    confirm "$2"
  else
    printf '  %s? %s [--auto: %s]%s\n' "$YELLOW" "$2" "$1" "$RESET"
    [[ "$1" == y ]]
  fi
}

UPSTREAM_REPO="UKGovernmentBEIS/inspect_ai"
VERSION_FILE="src/inspect_ai/tool/_sandbox_tools_utils/sandbox_tools_version.txt"
SUMS_FILE="src/inspect_ai/tool/_sandbox_tools_utils/SHA256SUMS"
BUCKET_BASE_URL="https://inspect-sandbox-tools.s3.us-east-2.amazonaws.com"
VARIANTS="amd64 arm64 amd64-musl arm64-musl"

# Resume support: after a successful build (and validation), a fingerprint of
# what was built (validated) is recorded in a state file that lives — and is
# gitignored — alongside the binaries. A later run skips a stage only when the
# fingerprint still matches exactly; any ambiguity (no record, changed source,
# untracked files among the build inputs) errs on the side of redoing the
# work, because publishing stale bytes under a version number is
# unrecoverable.
BUILD_SRC_PATHS="src/inspect_sandbox_tools src/inspect_ai/tool/_sandbox_tools_utils"

_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum | awk '{print $1}'
  else shasum -a 256 | awk '{print $1}'; fi
}

# build_fingerprint — hash of the worktree state of the build inputs (index
# listing + unstaged diff). SHA256SUMS is excluded: it's release output the
# build never reads, and including it would force a rebuild whenever the
# upload step rewrites it. Prints nothing when untracked files make the
# inputs unhashable.
build_fingerprint() {
  # shellcheck disable=SC2086
  [[ -z "$(git ls-files --others --exclude-standard -- $BUILD_SRC_PATHS)" ]] || return 0
  {
    # shellcheck disable=SC2086
    git ls-files -s -- $BUILD_SRC_PATHS ":(exclude)$SUMS_FILE"
    # shellcheck disable=SC2086
    git diff -- $BUILD_SRC_PATHS ":(exclude)$SUMS_FILE"
  } | _sha256
}

# artifacts_fingerprint — combined hash of the four artifact files.
artifacts_fingerprint() {
  local f
  for f in $VARIANTS; do
    _sha256 < "src/inspect_ai/binaries/inspect-sandbox-tools-$f-v$V"
  done | _sha256
}

# state_get/state_set — read/upsert KEY=VALUE in $STATE_FILE.
state_get() { grep -E "^$1=" "$STATE_FILE" 2>/dev/null | tail -n1 | cut -d= -f2-; }
state_set() {
  local tmp; tmp=$(mktemp)
  { grep -vE "^$1=" "$STATE_FILE" 2>/dev/null || true; printf '%s=%s\n' "$1" "$2"; } > "$tmp"
  # In a fresh checkout the (gitignored) binaries dir doesn't exist yet.
  mkdir -p "$(dirname "$STATE_FILE")"
  mv "$tmp" "$STATE_FILE"
}

TITLE="Sandbox tools release"
if [[ "$DRY_RUN" == 1 ]]; then TITLE="$TITLE — DRY RUN (no S3 upload)"; fi
banner "$TITLE"

# ── Stage 1: preconditions ────────────────────────────────────────────────
stage "Preconditions"
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
PYTHON="$ROOT/.venv/bin/python"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
say "Repo:   $ROOT"
say "Branch: $BRANCH"

if [[ "$BRANCH" == "main" ]]; then
  warn "You're on main. Binaries must be built from the PR's head branch —"
  warn "check it out (a worktree is ideal) and re-run this wizard."
  exit 1
fi
if ! confirm_or y "Is '$BRANCH' the head branch of the PR being landed?"; then
  warn "Check out the PR's head branch, then re-run."
  exit 1
fi

say "Checking that the PR is approved..."
PR_NUMBER=""
REVIEW_DECISION=""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  # gh pr view <branch> can't resolve cross-fork heads; pr list --head can.
  read -r PR_NUMBER REVIEW_DECISION < <(gh pr list --repo "$UPSTREAM_REPO" \
    --head "$BRANCH" --state open --json number,reviewDecision \
    --jq '"\(.[0].number // "") \(.[0].reviewDecision // "")"' 2>/dev/null) || true
fi
if [[ "$REVIEW_DECISION" == "APPROVED" ]]; then
  say "✓ PR #$PR_NUMBER is approved."
elif [[ "$DRY_RUN" == 1 ]]; then
  warn "PR IS NOT APPROVED (review decision: ${REVIEW_DECISION:-unknown — no PR found or gh unavailable})."
  warn "Continuing because this is a dry run — a real release requires an approved PR."
else
  warn "PR is not approved (review decision: ${REVIEW_DECISION:-unknown — no PR found or gh unavailable})."
  warn "Get the PR approved, then re-run."
  exit 1
fi

if [[ ! -x "$PYTHON" ]]; then
  warn "No repo venv at .venv/bin/python — create it and install deps first."
  exit 1
fi
if [[ "$DRY_RUN" == 0 ]] && ! command -v aws >/dev/null 2>&1; then
  warn "The aws CLI is required for the S3 upload — install it first."
  exit 1
fi

while ! docker info >/dev/null 2>&1; do
  warn "Docker isn't running."
  if [[ "$AUTO" == 1 ]]; then
    warn "Start Docker, then re-run."
    exit 1
  fi
  pause "Start Docker, then press Enter to re-check"
done
if ! docker buildx version >/dev/null 2>&1; then
  warn "Docker buildx (multi-arch) is required and not available."
  exit 1
fi
say "✓ Docker is running with buildx."

note "Refreshing this branch from its remote..."
git fetch --quiet
UPSTREAM_REF=$(git rev-parse --abbrev-ref '@{u}' 2>/dev/null || true)
if [[ -n "$UPSTREAM_REF" ]] && [[ -n "$(git rev-list "HEAD..$UPSTREAM_REF" 2>/dev/null)" ]]; then
  warn "This branch is behind $UPSTREAM_REF — pull first so you build the exact"
  warn "code being merged, then re-run."
  exit 1
fi
note "Fetching origin/main to check the injectable version..."
git fetch --quiet origin main
MAIN_V=$(git show origin/main:"$VERSION_FILE" | tr -d '[:space:]')
LOCAL_V=$(tr -d '[:space:]' < "$VERSION_FILE")
EXPECTED_V=$((MAIN_V + 1))
if [[ "$LOCAL_V" == "$EXPECTED_V" ]]; then
  say "✓ Version bumped: origin/main has v$MAIN_V, this branch has v$LOCAL_V."
else
  warn "This branch has v$LOCAL_V but origin/main has v$MAIN_V — check-version-bump"
  warn "CI requires exactly v$EXPECTED_V. Commit the bump to"
  warn "$VERSION_FILE on the PR branch, then re-run."
  exit 1
fi
V=$LOCAL_V
STATE_FILE="src/inspect_ai/binaries/.release-wizard-state-v$V"

# SHA256SUMS is excluded: it's release output (rewritten by the upload step,
# including on dry runs), not a build input.
if [[ -n "$(git status --porcelain --untracked-files=no -- . ":(exclude)$SUMS_FILE")" ]]; then
  warn "Working tree has uncommitted changes — binaries must be built from the"
  warn "exact code being merged."
  confirm_or n "Continue anyway?" || exit 1
fi
pause

# ── Stage 2: build the four artifacts ─────────────────────────────────────
stage "Build (slow — Docker builds for 4 variants, can exceed 10 minutes)"
SRC_FP=$(build_fingerprint || true)
BUILD_NEEDED=1
ALL_PRESENT=1
for f in $VARIANTS; do
  [[ -f "src/inspect_ai/binaries/inspect-sandbox-tools-$f-v$V" ]] || ALL_PRESENT=0
done
if [[ "$ALL_PRESENT" == 1 && -n "$SRC_FP" && "$(state_get built_from)" == "$SRC_FP" ]]; then
  say "✓ All four v$V artifacts exist and were built from this exact source"
  say "  (recorded fingerprint matches) — skipping the rebuild."
  if ! confirm_or n "Rebuild anyway?"; then
    BUILD_NEEDED=0
  fi
elif [[ "$ALL_PRESENT" == 1 ]]; then
  note "v$V artifacts exist, but there's no record they were built from this"
  note "checkout's current source — rebuilding to be safe."
fi
if [[ "$BUILD_NEEDED" == 1 ]]; then
  say "The four variants build in parallel; per-variant results print as they"
  say "finish (full log shown on failure)."
  pause "Press Enter to start the build"
  # Invalidate the stamps up front so a crash mid-build can't leave a stale
  # record paired with partially rewritten artifacts.
  state_set built_from building
  state_set validated ""
  if ! "$PYTHON" src/inspect_ai/tool/_sandbox_tools_utils/build_within_container.py --all --dev=false; then
    warn "Build failed — fix the error above and re-run the wizard."
    exit 1
  fi
  # Record the fingerprint only if the source is unchanged since the build
  # started; otherwise leave it unmatched so the next run rebuilds.
  POST_FP=$(build_fingerprint || true)
  if [[ -n "$POST_FP" && "$POST_FP" == "$SRC_FP" ]]; then
    state_set built_from "$POST_FP"
  else
    state_set built_from ambiguous
    warn "Couldn't record a trustworthy fingerprint (build inputs changed mid-build,"
    warn "or untracked files sit among them) — the next run will rebuild."
  fi
fi
say "Checking artifacts:"
MISSING=0
for f in $VARIANTS; do
  a="src/inspect_ai/binaries/inspect-sandbox-tools-$f-v$V"
  if [[ -f "$a" ]]; then
    note "✓ $a ($(du -h "$a" | cut -f1 | tr -d ' '))"
  else
    warn "missing: $a"
    MISSING=1
  fi
done
if [[ "$MISSING" == 1 ]]; then
  warn "Not all four artifacts were produced — aborting."
  exit 1
fi
note "(These are gitignored — never commit them.)"
pause

# ── Stage 3: validate across distros ──────────────────────────────────────
stage "Validate across distros (slow)"
say "Runs each artifact's healthcheck in Docker: glibc on Ubuntu 16.04–24.04,"
say "Debian 11/12, Kali; musl on Alpine 3.16/3.18/latest. Every distro must pass."
ART_FP=$(artifacts_fingerprint || true)
RUN_VALIDATION=1
if [[ -n "$ART_FP" && "$(state_get validated)" == "$ART_FP" ]]; then
  say "✓ These exact artifact bytes already passed validation — skipping."
  if ! confirm_or n "Re-validate anyway?"; then
    RUN_VALIDATION=0
  fi
fi
if [[ "$RUN_VALIDATION" == 1 ]]; then
  pause "Press Enter to start validation"
  if ! "$PYTHON" -m inspect_ai.tool._sandbox_tools_utils.validate_distros; then
    warn "Validation failed — any distro failure blocks the release. Aborting."
    exit 1
  fi
  say "✓ All distros passed."
  if [[ -n "$ART_FP" ]]; then
    state_set validated "$ART_FP"
  fi
fi
pause

# ── Stage 4: upload to S3 ─────────────────────────────────────────────────
stage "Upload to S3"
say "Uploads all four artifacts to s3://inspect-sandbox-tools/ (public-read),"
say "rewrites $SUMS_FILE, and round-trip verifies each object."
if [[ "$DRY_RUN" == 1 ]]; then
  say "Dry run — hashing, checking immutability against S3 (public reads, no"
  say "credentials), and writing $SUMS_FILE locally; no upload."
  if ! "$PYTHON" src/inspect_ai/tool/_sandbox_tools_utils/upload_to_s3.py "$V" --dry-run; then
    warn "Dry-run upload checks failed — see above."
    exit 1
  fi
else
  if [[ -n "${AWS_PROFILE:-}" ]]; then
    note "Using AWS_PROFILE=$AWS_PROFILE from your environment."
  elif [[ "$AUTO" == 1 ]]; then
    note "No AWS_PROFILE set — using default credentials."
  else
    ask AWS_PROFILE_IN "AWS profile for the upload (Enter to use default credentials):"
    if [[ -n "${AWS_PROFILE_IN:-}" ]]; then
      export AWS_PROFILE="$AWS_PROFILE_IN"
    fi
  fi
  while ! aws sts get-caller-identity >/dev/null 2>&1; do
    warn "AWS credentials are missing or stale."
    if [[ "$AUTO" == 1 ]]; then
      warn "Run 'aws sso login', then re-run."
      exit 1
    fi
    if confirm "Run 'aws sso login' now?"; then
      aws sso login || true
    else
      pause "Get credentials in another terminal, then press Enter to re-check"
    fi
  done
  say "✓ AWS credentials OK."
  if ! "$PYTHON" src/inspect_ai/tool/_sandbox_tools_utils/upload_to_s3.py "$V"; then
    warn "Upload aborted. If it hit the immutability guard (v$V already published"
    warn "with different bytes), never force over it — bump the version and publish"
    warn "fresh artifacts."
    exit 1
  fi
  say "✓ Uploaded and verified all four artifacts."
fi
pause

# ── Stage 5: commit and push the pinned digests ───────────────────────────
stage "Commit and push digests"
say "slow-tool-tests-release verifies the S3 objects against the committed"
say "digests, so it stays red until $SUMS_FILE lands on the PR branch."
if [[ "$DRY_RUN" == 1 ]]; then
  note "Dry run — $SUMS_FILE was rewritten locally for inspection, but nothing"
  note "was uploaded, so it must not be committed yet. Skipping."
else
  CHANGED=$(git status --porcelain -- "$SUMS_FILE")
  if [[ -z "$CHANGED" ]]; then
    say "✓ Nothing to commit — digests are already committed."
  else
    git --no-pager diff -- "$SUMS_FILE"
    if confirm_or y "Commit the change above to '$BRANCH' and push?"; then
      git add "$SUMS_FILE"
      git commit -m "Pin sandbox-tools v$V artifact digests"
      git push
      say "✓ Pushed."
    else
      SKIPPED+=("commit+push $SUMS_FILE — CI stays red until it lands on the PR branch")
      warn "Skipped — remember to commit and push it yourself."
    fi
  fi
fi
pause

# ── Stage 6: verify the published artifacts ───────────────────────────────
stage "Verify published artifacts"
say "Downloads all four public objects and checks them against the committed"
say "digest file (no credentials needed)."
if [[ "$DRY_RUN" == 1 ]]; then
  note "Dry run — nothing was published. Skipping."
else
  VERIFY_DIR=$(mktemp -d)
  for f in $VARIANTS; do
    name="inspect-sandbox-tools-$f-v$V"
    note "downloading $name..."
    if ! curl -fsSL -o "$VERIFY_DIR/$name" "$BUCKET_BASE_URL/$name"; then
      warn "Download failed for $name — is the upload complete?"
      exit 1
    fi
  done
  if command -v sha256sum >/dev/null 2>&1; then
    (cd "$VERIFY_DIR" && sha256sum -c "$ROOT/$SUMS_FILE")
  else
    (cd "$VERIFY_DIR" && shasum -a 256 -c "$ROOT/$SUMS_FILE")
  fi || {
    warn "Digest mismatch — do NOT merge; retry the upload before committing SHA256SUMS."
    exit 1
  }
  rm -rf "$VERIFY_DIR"
  say "✓ All four published artifacts match the committed digests."
fi
pause

# ── Stage 7: get CI green ─────────────────────────────────────────────────
stage "Get CI green"
if [[ "$DRY_RUN" == 1 ]]; then
  note "Dry run complete — build and validation passed. Re-run without --dry-run"
  note "to upload, commit the digests, and get CI green."
else
  say "The digest push triggers a fresh CI run; slow-tool-tests-release should"
  say "now pass. Merging then happens through the normal review process —"
  say "PyPI bundling is automatic at inspect_ai release time."
  if [[ -n "$PR_NUMBER" ]]; then
    if confirm_or n "Watch the PR's checks now (blocks until they finish)?"; then
      gh pr checks "$PR_NUMBER" --repo "$UPSTREAM_REPO" --watch || \
        warn "Some checks failed — investigate before merging."
    else
      note "Later: gh pr checks $PR_NUMBER --repo $UPSTREAM_REPO --watch"
    fi
  else
    SKIPPED+=("verify PR checks pass (gh unavailable — use the PR page on GitHub)")
    warn "gh not available/authenticated — check the PR page on GitHub."
  fi
fi
# ──────────────────────────────────────────────────────────────────────────

finish
