project:
  type: meridianlabs-ai/inspect-docs
  resources:
    - CNAME
    - listing/

inspect-docs:
  title: Inspect
  description: Open-source framework for large language model evaluations
  image: /images/inspect.png
  logo: images/aisi-logo.svg
  favicon: favicon.svg
  url: https://inspect.aisi.org.uk
  module: inspect_ai
  repo: UKGovernmentBEIS/inspect_ai
  org: UK AI Security Institute
  org_url: https://aisi.gov.uk
  twitter: AISecurityInst
  sidebar:
    collapse-level: 1
  navbar:
    left:
      - text: "User Guide"
        menu:
          - text: Basics
            href: index.qmd
          - text: Components
            href: tasks.qmd
          - text: Models
            href: models.qmd
          - text: Scoring
            href: scoring.qmd
          - text: Agents
            href: agents.qmd
          - text: Tools
            href: tools.qmd
          - text: Running
            href: running.qmd
          - text: Analysis
            href: analysis.qmd
          - text: Extensions
            href: extensions.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "Extensions"
        href: extensions/index.qmd
      - text: "Evals"
        href: evals/index.qmd
  navigation:
    - text: Basics
      contents:
        - text: Welcome
          href: index.qmd
        - href: tutorial.qmd
        - href: options.qmd
        - href: log-viewer.qmd
        - text: VS Code
          href: vscode.qmd
    - text: Components
      contents:
        - href: tasks.qmd
        - href: datasets.qmd
        - href: solvers.qmd
        - href: scorers.qmd
    - text: Models
      contents:
        - href: models.qmd
        - text: Providers
          href: providers.qmd
        - href: caching.qmd
        - text: Concurrency
          href: models-concurrency.qmd
        - href: compaction.qmd
        - href: multimodal.qmd
        - href: reasoning.qmd
        - href: structured.qmd
        - href: models-batch.qmd
    - text: Scoring
      href: scoring.qmd
      contents:
        - href: standard-scorers.qmd
        - href: custom-scorers.qmd
        - text: Model Grading
          href: model-graded.qmd
        - text: Scoring Metrics
          href: metrics.qmd
        - href: multiple-scorers.qmd
        - href: scoring-workflow.qmd
        - href: perplexity.qmd
    - text: Agents
      contents:
        - href: agents.qmd
        - href: react-agent.qmd
        - href: deepagent.qmd
        # - text: Checkpointing
        #   href: checkpointing.qmd
        - text: Intervention
          href: intervention.qmd
        - href: multi-agent.qmd
        - href: agent-custom.qmd
        - href: agent-bridge.qmd
        - href: human-agent.qmd
    - text: Tools
      contents:
        - href: tools.qmd
        - href: tools-standard.qmd
        - text: MCP Tools
          href: tools-mcp.qmd
        - href: tools-custom.qmd
        - href: sandboxing.qmd
        - href: approval.qmd
    - text: Running
      href: running.qmd
      contents:
        - href: eval-sets.qmd
        - href: parallelism.qmd
        - href: handling-errors.qmd
        - href: setting-limits.qmd
        - href: early-stopping.qmd
        - href: tracing.qmd   
    - text: Analysis
      href: analysis.qmd
      contents:
        - href: eval-logs.qmd
        - text: Dataframes
          href: dataframe.qmd
        - href: scanners.qmd
        - href: inspect-viz.qmd
        - href: task-views.qmd
    - text: Extensions
      href: extensions.qmd
      contents:
        - text: Model APIs
          href: extensions-model-api.qmd
        - text: Components
          href: extensions-components.qmd
        - text: Sandboxes
          href: extensions-sandboxes.qmd
        - text: Approvers
          href: extensions-approvers.qmd
        - text: Hooks
          href: extensions-hooks.qmd
        - text: Filesystems
          href: extensions-filesystems.qmd

format:
  inspect-docs-html:
    code-annotations: select
    css: styles.css

execute:
  enabled: false
