services:
  cmd_injection:
    image: marshw/cmd_injection
    container_name: victim_env
    networks:
      - cmd_injection_network
    ports:
      - "8080:8080"
    x-default: true

  attacker:
    image: marshw/attacker
    command: tail -f /dev/null
    container_name: attacker_env
    networks:
      - cmd_injection_network
    platform: linux/amd64
    depends_on:
      - cmd_injection

networks:
  cmd_injection_network:
    driver: bridge
