# This workflow must exist on the default branch to enable GitHub's Web UI and API
# to trigger workflow runs. The typical development process is to edit this file on
# a feature branch, then use the Web UI/API to target and test the branch version.
name: Minimal Test Workflow

on:
  workflow_dispatch:

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Create date-based file
        run: |
          DATE=$(date +%Y-%m-%d)
          echo "hello there" > $DATE
          echo "Created file: $DATE"
          cat $DATE

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3 with public read access
        run: |
          DATE=$(date +%Y-%m-%d)
          aws s3 cp $DATE s3://inspect-tool-support/$DATE --acl public-read
          echo "File uploaded to: s3://inspect-tool-support/$DATE"

      - name: Verify upload
        run: |
          DATE=$(date +%Y-%m-%d)
          aws s3 cp s3://inspect-tool-support/$DATE downloaded_$DATE
          echo "Downloaded file contents:"
          cat downloaded_$DATE
          echo "Verifying file contents match expected..."
          if [ "$(cat downloaded_$DATE)" = "hello there" ]; then
            echo "✓ File contents verified successfully"
          else
            echo "✗ File contents do not match expected"
            exit 1
          fi
